name: CI
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: CI=true npm run test
      - name: Run tests (e2e)
        run: CI=true npm run test:e2e
